### ISSUE TITLE
Consider adding two related papers to the list

### ISSUE THREAD

**Issue by linlany** [LucyDYu/Awesome-Multimodal-Continual-Learning#1]
Hi, thank you for maintaining this helpful repository. 

Could you please add the following two papers to this paper list: 
Generative Multi-modal Models are Good Class Incremental Learners (CVPR24) [https://arxiv.org/abs/2403.18383](url) and Class-Incremental Learning with CLIP: Adaptive Representation Adjustment and Parameter Fusion (ECCV24) [https://arxiv.org/abs/2407.14143](url). 

Thanks for your consideration!

**Comment by LucyDYu** [comment]
Thank you for your contribution. The repository has been updated accordingly.
